### ISSUE TITLE
GFX: border shadow remains when opening and closing systray (or kickoff menu) 2xtimes

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook-remix#47]
also happens with main menu, and outside of pinebook context

**Comment by subdiff** [comment]
Thanks to @davidedmundson's hint I discovered a fix by not doing Pixmap exchanges in the xf86-video-armsoc driver and instead just blit the update. This can be done by disabling the branch starting from here: https://github.com/shadeslayer/xf86-video-armsoc/blob/master/src/armsoc_dri2.c#L930

I did further tests, to pinpoint the issue more exactly, but these gave no results. In general the deeper issue with this path might be in Qt or the Xserver DIX code itself.

Just not trying to exchange Pixmaps could degrade performance since blits are expected to be more expensive to my knowledge, but in my tests I didn't saw a difference. As a simple solution for now I would therefore recommend to just disable the code path.

**Comment by bhush9** [comment]
Fixed in http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180212-1552/

**Comment by bhush9** [comment]
(sorry for labeling mess.. I restored previous state of ticket)

**Comment by star-buck** [comment]
seems fixed!
