### ISSUE TITLE
GFX: allow Video up to 720dpi (mpv/smplayer in fullscreen+window-mode, youtube playback)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook-remix#50]

**Comment by star-buck** [comment]
- Why does Qml have such a bad performance, if not GPU powered for simple stuff like loading
system settings?
- Is it related to the listview default?

**Comment by star-buck** [comment]
Sounds truly awesome if working as described.

**Comment by star-buck** [comment]
Needs fixing in kwin?

**Comment by star-buck** [comment]
Would that temp fix have any visible drawbacks?
Does it work with smplayer then?

**Comment by star-buck** [comment]
@davidedmundson : any update on this, regarding smplayer and window-mode?

**Comment by davidedmundson** [comment]
So there are multiple things in progress. It's also very scattered and messy, but I don't think there's any other way of working as I don't know what will work till after.

On FBTurbo:
  - I tried getting that on our Neon installations. I can get images, but the modeline is all wrong, so it's all diagonal. It seems this comes from uEnv setting low level parameters, but I can't immediately find the difference.

 - Using the mate image, I was playing with fbturbo. When I enable proper GL drivers and try and use it X crashes (which we knew) but now I know why. It seems it's missing an entire kernel module, ump. This module doesn't compile on Arch64..but maybe that's fixable. It's on my queue to try that.


---
On our stack. Within mpv I have two semi-working modes.

Decoding on the VE, then mpv doing the rendering in GL then via the normal X stack. (mpv hwdec=vdpau-copy vo=gpu),  which is what you've played with. This works fine from MPVs POV, but we use up loads of CPU in X copying about. My current plan is to copy fbturbo's copying code (cpu-backend.c) which should in theory do copies a lot faster. There's also code in fbturbo's dri code to copy which does an optimisation when a window isn't obscured.

----

There's also the mode where we do the overlay directly (vo=fdpau). This ultimately isn't faster because of my slow conversion I can't fix, but it does avoid any X overhead. If I can't fix X, I can improve this.

**Comment by davidedmundson** [comment]
>There's also the mode where we do the overlay directly (vo=fdpau). This ultimately isn't faster because of my slow conversion I can't fix, but it does avoid any X overhead. If I can't fix X, I can improve this.

It would be the last one on my list :/.
I fixed my overlay rendering code branch. 

It now renders the 1080p star wars trailer in a window / smplayer dropping between 10 and 100 frames, which I'm not sure I'd notice if I didn't have a log open.

This approach means we actually don't need to rebuild mpv. But given we already have..don't know.

Note this version of fixing things has the same issues that we see on Mate, dragging the video window or putting a window on top leaves the video overlayed in the wrong place.

Packaging might take a day, should get an image Friday.

**Comment by star-buck** [comment]
1080 is not important.
Dropping 10 to 100 frames is also not an improvement?

Lets focus on 720dpi for smplayer in fullscreen+window mode.

**Comment by davidedmundson** [comment]
To clarify I'm saying it's on par with Mate at decoding a 1080p video, it can naturally then do 720 fine. This is in a window or smplayer.

So to summarise: 

Before Fosdem we had hardware decoding + GPU rendering.

Now I  do effectively the same hardware overlay rendering that we see in the Mate image. But that comes with the same drawbacks when moving the video window. 

---

Things have been fine on my dev SD card, but I'm having various problems with deployment.

---
Latest code with packaging folders:
https://github.com/davidedmundson/libvdpau-sunxi/tree/wpackaging   
https://github.com/davidedmundson/libyuv

**Comment by star-buck** [comment]
Alright, I tested with a fresh install from last img 20180130 + removing + re-adding + updating all packages and the result seems quite nice.

I suggest @bhush9 or @jriddell to do a new img so we can test this on a complete install and will also add a new ticket with some of the settings for smplayer to make for the best experience.
After new img confirmed working, lets mark this ticket ready and move, if shadow also is fixed, release img early next week with release promo from sebas.

**Comment by star-buck** [comment]
one thing that is now visibly noticeable is there are "fine line frizzles" during all faster transitions, which look annoying.
Those are not there on playing the same video on netrunner pinebook or if video is played back on x86, so those come from whatever the update did to decode the video.

**Comment by star-buck** [comment]
I will download again the last netrunner img from here:
http://ds9-eu.s3-website.eu-central-1.amazonaws.com/#!/dci%2Fimages%2F1801%2Farm64%2Fnetrunner-pinebook%2F

install fresh and apply the tricks and compare both video playback on smplayer.
Maybe we can gain some knowledge we can make the video playback on neon perfect without the two drawbacks, that is no overlay and that annyoing frizzle FX, which i recall shouldnt be there on that last netrunner img.

**Comment by bhush9** [comment]
> I suggest @bhush9 or @jriddell to do a new img so we can test this on a complete install and will also add a new ticket with some of the settings for smplayer to make for the best experience.

re: while you were testing this, a new image was work in progress, http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180209-1549/

Please test.

**Comment by star-buck** [comment]
other than the missing smplayer settings (see other ticket), this works after manually applying them.

Now the things that could be improved are:
- video output shows visible frizzles (aka thin horizontal lines) for all faster moving "sharp borders"
- video cannot be overlayed with menu popus, etc.
- a simple song mp3 doesnt show standstill video img (will show what i mean in the video comparison)
- firefox: youtube does not play videos smoothly, 720dpi almost unwatchable (i assume it is using opengl and not vdpau?)

Anyhow, its getting there, a big thanks and kudos to David up to this point for providing these approaches for testing!

**Comment by star-buck** [comment]
@davidedmundson : Does youtube need a special configuration? Or each browser, like firefox, chromium, etc.?
I recall youtube being smooth up to 720dpi in browser or fullscreen at one point...

**Comment by star-buck** [comment]
continuing in two seperate tickets not to confuse those two approaches and related drawbacks.
